# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIAgregarEspecie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgregarEspecie(object):
    def setupUi(self, AgregarEspecie):
        AgregarEspecie.setObjectName("AgregarEspecie")
        AgregarEspecie.resize(498, 167)
        self.centralwidget = QtWidgets.QWidget(AgregarEspecie)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 40, 191, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 100, 191, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 80, 55, 16))
        self.label_2.setObjectName("label_2")
        self.btnAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(330, 70, 93, 28))
        self.btnAgregar.setObjectName("btnAgregar")
        AgregarEspecie.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AgregarEspecie)
        self.statusbar.setObjectName("statusbar")
        AgregarEspecie.setStatusBar(self.statusbar)
        #Accion del boton
        self.btnAgregar.clicked.connect(self.addEspecie)

        self.retranslateUi(AgregarEspecie)
        QtCore.QMetaObject.connectSlotsByName(AgregarEspecie)

    def retranslateUi(self, AgregarEspecie):
        _translate = QtCore.QCoreApplication.translate
        AgregarEspecie.setWindowTitle(_translate("AgregarEspecie", "Agregar Especie"))
        self.label.setText(_translate("AgregarEspecie", "ID"))
        self.label_2.setText(_translate("AgregarEspecie", "Nombre"))
        self.btnAgregar.setText(_translate("AgregarEspecie", "Agregar"))

    
     #def addEspecie(self):
      #  ID = self.txtID.text()
      #  nom  = self.txtNombre.text()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarEspecie = QtWidgets.QMainWindow()
    ui = Ui_AgregarEspecie()
    ui.setupUi(AgregarEspecie)
    AgregarEspecie.show()
    sys.exit(app.exec_())
