# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIAgregarJugador.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
from zeep import Client 
url ="http://localhost:58999/Service/ServiceJugador.svc?wsdl"
cliente = Client(wsdl=url)
print(cliente)
class Ui_AgregarJugador(object):
    def setupUi(self, AgregarJugador):
        AgregarJugador.setObjectName("AgregarJugador")
        AgregarJugador.resize(305, 429)
        self.centralwidget = QtWidgets.QWidget(AgregarJugador)
        self.centralwidget.setObjectName("centralwidget")
        self.txtID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtID.setGeometry(QtCore.QRect(60, 70, 181, 22))
        self.txtID.setObjectName("txtID")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 220, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 270, 55, 16))
        self.label_5.setObjectName("label_5")
        self.txtCuenta = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCuenta.setGeometry(QtCore.QRect(60, 130, 181, 22))
        self.txtCuenta.setObjectName("txtCuenta")
        self.txtContrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContrasena.setGeometry(QtCore.QRect(60, 190, 181, 22))
        self.txtContrasena.setObjectName("txtContrasena")
        self.txtApodo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtApodo.setGeometry(QtCore.QRect(60, 240, 181, 22))
        self.txtApodo.setObjectName("txtApodo")
        self.txtEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEmail.setGeometry(QtCore.QRect(60, 290, 181, 22))
        self.txtEmail.setObjectName("txtEmail")
        self.btnAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(110, 370, 93, 28))
        self.btnAgregar.setObjectName("btnAgregar")
        AgregarJugador.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AgregarJugador)
        self.statusbar.setObjectName("statusbar")
        AgregarJugador.setStatusBar(self.statusbar)
        #Accion del boton
        self.btnAgregar.clicked.connect(self.addJugador)

        self.retranslateUi(AgregarJugador)
        QtCore.QMetaObject.connectSlotsByName(AgregarJugador)
        print(cliente)
        
         

    def retranslateUi(self, AgregarJugador):
        _translate = QtCore.QCoreApplication.translate
        AgregarJugador.setWindowTitle(_translate("AgregarJugador", "Agregar Jugador"))
        self.label.setText(_translate("AgregarJugador", "ID"))
        self.label_2.setText(_translate("AgregarJugador", "Cuenta"))
        self.label_3.setText(_translate("AgregarJugador", "Contraseña"))
        self.label_4.setText(_translate("AgregarJugador", "Apodo"))
        self.label_5.setText(_translate("AgregarJugador", "Email"))
        self.btnAgregar.setText(_translate("AgregarJugador", "Agregar"))

    def addJugador(self):
        ID = self.txtID.text()
        cuen = self.txtCuenta.text()
        contra = self.txtContrasena.text()
        apo = self.txtApodo.text()
        email = self.txtEmail.text()
        estReg = 1
        FechaReg = "2021/10/23"
        cliente.service.InsertJugador(ID, cuen, contra, apo, email,estReg,FechaReg)
    
        
        

        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarJugador = QtWidgets.QMainWindow()
    ui = Ui_AgregarJugador()
    ui.setupUi(AgregarJugador)
    AgregarJugador.show()
    sys.exit(app.exec_())
