# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIAgregarPersonaje.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgregarPersonaje(object):
    def setupUi(self, AgregarPersonaje):
        AgregarPersonaje.setObjectName("AgregarPersonaje")
        AgregarPersonaje.resize(322, 496)
        self.centralwidget = QtWidgets.QWidget(AgregarPersonaje)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 55, 16))
        self.label.setObjectName("label")
        self.btnAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(120, 430, 93, 28))
        self.btnAgregar.setObjectName("btnAgregar")
        self.txtID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtID.setGeometry(QtCore.QRect(70, 60, 181, 22))
        self.txtID.setObjectName("txtID")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 150, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 200, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 250, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 300, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 350, 55, 16))
        self.label_7.setObjectName("label_7")
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setGeometry(QtCore.QRect(70, 120, 181, 22))
        self.txtNombre.setObjectName("txtNombre")
        self.txtFuerza = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFuerza.setGeometry(QtCore.QRect(70, 170, 181, 22))
        self.txtFuerza.setObjectName("txtFuerza")
        self.txtMana = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMana.setGeometry(QtCore.QRect(70, 220, 181, 22))
        self.txtMana.setObjectName("txtMana")
        self.txtEnergia = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEnergia.setGeometry(QtCore.QRect(70, 270, 181, 22))
        self.txtEnergia.setObjectName("txtEnergia")
        self.cbEspecie = QtWidgets.QComboBox(self.centralwidget)
        self.cbEspecie.setGeometry(QtCore.QRect(70, 320, 181, 22))
        self.cbEspecie.setObjectName("cbEspecie")
        self.cbJugador = QtWidgets.QComboBox(self.centralwidget)
        self.cbJugador.setGeometry(QtCore.QRect(70, 370, 181, 22))
        self.cbJugador.setObjectName("cbJugador")
        AgregarPersonaje.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AgregarPersonaje)
        self.statusbar.setObjectName("statusbar")
        AgregarPersonaje.setStatusBar(self.statusbar)
        #Accion del boton
        self.btnAgregar.clicked.connect(self.addPersonaje)

        self.retranslateUi(AgregarPersonaje)
        QtCore.QMetaObject.connectSlotsByName(AgregarPersonaje)

    def retranslateUi(self, AgregarPersonaje):
        _translate = QtCore.QCoreApplication.translate
        AgregarPersonaje.setWindowTitle(_translate("AgregarPersonaje", "Agregar Personaje"))
        self.label.setText(_translate("AgregarPersonaje", "ID"))
        self.btnAgregar.setText(_translate("AgregarPersonaje", "Agregar"))
        self.label_2.setText(_translate("AgregarPersonaje", "Nombre"))
        self.label_3.setText(_translate("AgregarPersonaje", "Fuerza"))
        self.label_4.setText(_translate("AgregarPersonaje", "Mana"))
        self.label_5.setText(_translate("AgregarPersonaje", "Energia"))
        self.label_6.setText(_translate("AgregarPersonaje", "Especie"))
        self.label_7.setText(_translate("AgregarPersonaje", "Jugador"))


   


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarPersonaje = QtWidgets.QMainWindow()
    ui = Ui_AgregarPersonaje()
    ui.setupUi(AgregarPersonaje)
    AgregarPersonaje.show()
    sys.exit(app.exec_())
