# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIActualizarPersonaje.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActualizarPersonaje(object):
    def setupUi(self, ActualizarPersonaje):
        ActualizarPersonaje.setObjectName("ActualizarPersonaje")
        ActualizarPersonaje.resize(334, 495)
        self.centralwidget = QtWidgets.QWidget(ActualizarPersonaje)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 290, 55, 16))
        self.label_6.setObjectName("label_6")
        self.cbEspecie = QtWidgets.QComboBox(self.centralwidget)
        self.cbEspecie.setGeometry(QtCore.QRect(70, 310, 181, 22))
        self.cbEspecie.setObjectName("cbEspecie")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 340, 55, 16))
        self.label_7.setObjectName("label_7")
        self.btnActualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnActualizar.setGeometry(QtCore.QRect(50, 420, 93, 28))
        self.btnActualizar.setObjectName("btnActualizar")
        self.txtID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtID.setGeometry(QtCore.QRect(70, 50, 181, 22))
        self.txtID.setObjectName("txtID")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 140, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 190, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 240, 55, 16))
        self.label_5.setObjectName("label_5")
        self.txtMana = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMana.setGeometry(QtCore.QRect(70, 210, 181, 22))
        self.txtMana.setObjectName("txtMana")
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setGeometry(QtCore.QRect(70, 110, 181, 22))
        self.txtNombre.setObjectName("txtNombre")
        self.txtFuerza = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFuerza.setGeometry(QtCore.QRect(70, 160, 181, 22))
        self.txtFuerza.setObjectName("txtFuerza")
        self.cbJugador = QtWidgets.QComboBox(self.centralwidget)
        self.cbJugador.setGeometry(QtCore.QRect(70, 360, 181, 22))
        self.cbJugador.setObjectName("cbJugador")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 55, 16))
        self.label.setObjectName("label")
        self.txtEnergia = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEnergia.setGeometry(QtCore.QRect(70, 260, 181, 22))
        self.txtEnergia.setObjectName("txtEnergia")
        self.btnBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(180, 420, 93, 28))
        self.btnBuscar.setObjectName("btnBuscar")
        ActualizarPersonaje.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ActualizarPersonaje)
        self.statusbar.setObjectName("statusbar")
        ActualizarPersonaje.setStatusBar(self.statusbar)

            #Accion del boton
        self.btnActualizar.clicked.connect(self.updatePersonaje)

        self.retranslateUi(ActualizarPersonaje)
        QtCore.QMetaObject.connectSlotsByName(ActualizarPersonaje)

    def retranslateUi(self, ActualizarPersonaje):
        _translate = QtCore.QCoreApplication.translate
        ActualizarPersonaje.setWindowTitle(_translate("ActualizarPersonaje", "Actualizar Personaje"))
        self.label_6.setText(_translate("ActualizarPersonaje", "Especie"))
        self.label_7.setText(_translate("ActualizarPersonaje", "Jugador"))
        self.btnActualizar.setText(_translate("ActualizarPersonaje", "Actualizar"))
        self.label_2.setText(_translate("ActualizarPersonaje", "Nombre"))
        self.label_3.setText(_translate("ActualizarPersonaje", "Fuerza"))
        self.label_4.setText(_translate("ActualizarPersonaje", "Mana"))
        self.label_5.setText(_translate("ActualizarPersonaje", "Energia"))
        self.label.setText(_translate("ActualizarPersonaje", "ID"))
        self.btnBuscar.setText(_translate("ActualizarPersonaje", "Buscar"))

    def updatePersonaje(self):
        ID = self.txtID.text()
        nom  = self.txtNombre.text()
        fuer = self.txtFuerza.text()
        mana = self.txtMana.text()
        ener = self.txtEnergia.text()
        #espec = self.cbEspecie.text()
        #juga = self.cbJugador.text()
        estReg = 1
        FechaReg = 11111


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ActualizarPersonaje = QtWidgets.QMainWindow()
    ui = Ui_ActualizarPersonaje()
    ui.setupUi(ActualizarPersonaje)
    ActualizarPersonaje.show()
    sys.exit(app.exec_())
