# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIActualizarJugador.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActualizarJugador(object):
    def setupUi(self, ActualizarJugador):
        ActualizarJugador.setObjectName("ActualizarJugador")
        ActualizarJugador.resize(340, 417)
        self.centralwidget = QtWidgets.QWidget(ActualizarJugador)
        self.centralwidget.setObjectName("centralwidget")
        self.txtApodo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtApodo.setGeometry(QtCore.QRect(80, 210, 181, 22))
        self.txtApodo.setObjectName("txtApodo")
        self.btnActualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnActualizar.setGeometry(QtCore.QRect(50, 340, 93, 28))
        self.btnActualizar.setObjectName("btnActualizar")
        self.txtEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEmail.setGeometry(QtCore.QRect(80, 270, 181, 22))
        self.txtEmail.setObjectName("txtEmail")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 55, 16))
        self.label_2.setObjectName("label_2")
        self.btnBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(200, 340, 93, 28))
        self.btnBuscar.setObjectName("btnBuscar")
        self.txtID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtID.setGeometry(QtCore.QRect(80, 40, 181, 22))
        self.txtID.setObjectName("txtID")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 55, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 140, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 250, 55, 16))
        self.label_5.setObjectName("label_5")
        self.txtCuenta = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCuenta.setGeometry(QtCore.QRect(80, 100, 181, 22))
        self.txtCuenta.setObjectName("txtCuenta")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 190, 55, 16))
        self.label_4.setObjectName("label_4")
        self.txtContrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContrasena.setGeometry(QtCore.QRect(80, 160, 181, 22))
        self.txtContrasena.setObjectName("txtContrasena")
        ActualizarJugador.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ActualizarJugador)
        self.statusbar.setObjectName("statusbar")
        ActualizarJugador.setStatusBar(self.statusbar)

        #Accion del boton
        self.btnActualizar.clicked.connect(self.updateJugador)

        self.retranslateUi(ActualizarJugador)
        QtCore.QMetaObject.connectSlotsByName(ActualizarJugador)

    def retranslateUi(self, ActualizarJugador):
        _translate = QtCore.QCoreApplication.translate
        ActualizarJugador.setWindowTitle(_translate("ActualizarJugador", "Actualizar Jugador"))
        self.btnActualizar.setText(_translate("ActualizarJugador", "Actualizar"))
        self.label_2.setText(_translate("ActualizarJugador", "Cuenta"))
        self.btnBuscar.setText(_translate("ActualizarJugador", "Buscar"))
        self.label.setText(_translate("ActualizarJugador", "ID"))
        self.label_3.setText(_translate("ActualizarJugador", "Contraseña"))
        self.label_5.setText(_translate("ActualizarJugador", "Email"))
        self.label_4.setText(_translate("ActualizarJugador", "Apodo"))


    def updateJugador(self):
        ID = self.txtID.text()
        cuen = self.txtCuenta.text()
        contra = self.txtContrasena.text()
        apo = self.txtApodo.text()
        email = self.txtEmail.text()
        estReg = 1
        FechaReg = 11111
        print(ID, cuen, contra, apo, email, estReg, FechaReg)
   


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ActualizarJugador = QtWidgets.QMainWindow()
    ui = Ui_ActualizarJugador()
    ui.setupUi(ActualizarJugador)
    ActualizarJugador.show()
    sys.exit(app.exec_())
