# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIGraficar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraficarTodo(object):
    def setupUi(self, GraficarTodo):
        GraficarTodo.setObjectName("GraficarTodo")
        GraficarTodo.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(GraficarTodo)
        self.centralwidget.setObjectName("centralwidget")
        self.btnGraficar = QtWidgets.QPushButton(self.centralwidget)
        self.btnGraficar.setGeometry(QtCore.QRect(340, 530, 93, 28))
        self.btnGraficar.setObjectName("btnGraficar")
        self.GVGraficarTodo = QtWidgets.QGraphicsView(self.centralwidget)
        self.GVGraficarTodo.setGeometry(QtCore.QRect(20, 50, 751, 461))
        self.GVGraficarTodo.setObjectName("GVGraficarTodo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 30, 55, 16))
        self.label.setObjectName("label")
        GraficarTodo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GraficarTodo)
        self.statusbar.setObjectName("statusbar")
        GraficarTodo.setStatusBar(self.statusbar)

        self.retranslateUi(GraficarTodo)
        QtCore.QMetaObject.connectSlotsByName(GraficarTodo)

    def retranslateUi(self, GraficarTodo):
        _translate = QtCore.QCoreApplication.translate
        GraficarTodo.setWindowTitle(_translate("GraficarTodo", "Graficar"))
        self.btnGraficar.setText(_translate("GraficarTodo", "Graficar"))
        self.label.setText(_translate("GraficarTodo", "Graficar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraficarTodo = QtWidgets.QMainWindow()
    ui = Ui_GraficarTodo()
    ui.setupUi(GraficarTodo)
    GraficarTodo.show()
    sys.exit(app.exec_())
