# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIListarPersonajes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListarPersonajes(object):
    def setupUi(self, ListarPersonajes):
        ListarPersonajes.setObjectName("ListarPersonajes")
        ListarPersonajes.resize(890, 543)
        self.centralwidget = QtWidgets.QWidget(ListarPersonajes)
        self.centralwidget.setObjectName("centralwidget")
        self.btnListar = QtWidgets.QPushButton(self.centralwidget)
        self.btnListar.setGeometry(QtCore.QRect(390, 470, 93, 28))
        self.btnListar.setObjectName("btnListar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 10, 101, 21))
        self.label.setObjectName("label")
        self.tbListaJugadores = QtWidgets.QTableWidget(self.centralwidget)
        self.tbListaJugadores.setGeometry(QtCore.QRect(20, 40, 861, 411))
        self.tbListaJugadores.setObjectName("tbListaJugadores")
        self.tbListaJugadores.setColumnCount(0)
        self.tbListaJugadores.setRowCount(0)
        ListarPersonajes.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ListarPersonajes)
        self.statusbar.setObjectName("statusbar")
        ListarPersonajes.setStatusBar(self.statusbar)

        self.retranslateUi(ListarPersonajes)
        QtCore.QMetaObject.connectSlotsByName(ListarPersonajes)

    def retranslateUi(self, ListarPersonajes):
        _translate = QtCore.QCoreApplication.translate
        ListarPersonajes.setWindowTitle(_translate("ListarPersonajes", "Listar Personajes"))
        self.btnListar.setText(_translate("ListarPersonajes", "Listar"))
        self.label.setText(_translate("ListarPersonajes", "Lista Personajes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ListarPersonajes = QtWidgets.QMainWindow()
    ui = Ui_ListarPersonajes()
    ui.setupUi(ListarPersonajes)
    ListarPersonajes.show()
    sys.exit(app.exec_())
